/* 현재 TABLESPACE 사용량 조회 */
SELECT 
	A.TABLESPACE_NAME,
	A.TOTAL,
	NVL(ROUND((A.TOTAL - B.FREE), 2),A.TOTAL) "USED_MB",
	NVL(ROUND(B.FREE,2),0) "FREE_MB",
	NVL(ROUND((A.TOTAL - B.FREE) / A.TOTAL * 100 ,2) , 100) "USE_RATIO%"
--	,ROUND(CEIL((1/(0.8/NVL(ROUND((A.TOTAL - B.FREE), 2), A.TOTAL)) - A.TOTAL)),2) "NEED_TO_80PER_MB",
--	120 - NVL(ROUND(B.FREE,2) , 0 ) "NEED_ TO_120G_MB" 
FROM 
	(SELECT TABLESPACE_NAME, 
			SUM(BYTES) /1024/1024 "TOTAL" 
		FROM DBA_DATA_FILES  
		GROUP BY TABLESPACE_NAME ) A, 
	(SELECT TABLESPACE_NAME,
			SUM(BYTES) /1024/1024 "FREE" 
		FROM DBA_FREE_SPACE 
		GROUP BY TABLESPACE_NAME ) B 
WHERE A.TABLESPACE_NAME = B.TABLESPACE_NAME(+) 
	AND A.TABLESPACE_NAME LIKE 'TS_%'
ORDER BY TABLESPACE_NAME;


/* 현재 데이터 파일 SIZE 조회 */
SELECT FILE_NAME, TABLESPACE_NAME, ROUND(BYTES/1024/1024,2) SIZE_MB
FROM DBA_DATA_FILES WHERE TABLESPACE_NAME LIKE 'TS_%';


/* TABLESPACE 별 SEGMENT 합계 조회 */
SELECT TABLESPACE_NAME, SUM(BYTES)/1024/1024 SIZE_MB FROM DBA_SEGMENTS 
WHERE TABLESPACE_NAME LIKE 'TS_%' GROUP BY TABLESPACE_NAME ;	

/* SEGMENT SIZE 조회 */
SELECT OWNER, SEGMENT_NAME, SEGMENT_TYPE , TABLESPACE_NAME, ROUND(BYTES/1024/1024,2) SIZE_MB
FROM  DBA_SEGMENTS WHERE TABLESPACE_NAME LIKE 'TS_%';




