
--PL/SQL PROCEDURE

create or replace PROCEDURE PROC_OUT_CURSOR
(
TABLE_NM IN VARCHAR2
, CURSOR_NM OUT SYS_REFCURSOR
)
IS
TARGET_TABLE_NM VARCHAR2(100);

BEGIN
TARGET_TABLE_NM := TABLE_NM;

OPEN CURSOR_NM FOR
    SELECT  TABLE_NAME, COLUMN_NAME , COLUMN_ID, DATA_TYPE, DATA_LENGTH FROM USER_TAB_COLS
    WHERE TABLE_NAME = TARGET_TABLE_NM;

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('SQL ERROR MESSAGE: ' || SQLERRM);        
END;
--SQL

VAR CURSOR_NM REFCURSOR;
EXEC PROC_OUT_CURSOR('TBL1', :CURSOR_NM);
PRINT CURSOR_NM;
